#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_SINGLE_OUT_DIR="runs/sram_single"
DEFAULT_BATCH_OUT_DIR="runs/sram_batch"
SUMMARY_PATH=""
OUT_DIR=""

usage() {
  cat <<'EOF'
Usage:
  ./run_sram_analysis.sh single <config.conf> [--out-dir DIR] [--summary FILE]
  ./run_sram_analysis.sh batch  <batch.csv>   [--out-dir DIR] [--summary FILE]
  ./run_sram_analysis.sh help

Single config files use trusted Bash KEY=value syntax. Batch files use simple CSV
with no embedded commas or quoted commas.

Required single config keys:
  RUN_NAME, PORT_MODE, WIDTH_BITS, DEPTH_WORDS

Required batch CSV columns:
  run_name, port_mode, width_bits, depth_words

PORT_MODE values:
  single  -> one read/write port (1RW)
  dual    -> one exclusive read port plus one exclusive write port (1R1W)
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_tools() {
  local tool
  for tool in awk sed grep mkdir date make; do
    command -v "$tool" >/dev/null 2>&1 || die "required tool not found: $tool"
  done
}

ensure_cacti_binary() {
  if [[ -x "$SCRIPT_DIR/cacti" ]]; then
    return
  fi

  printf 'CACTI binary not found; running make...\n'
  (cd "$SCRIPT_DIR" && make)

  [[ -x "$SCRIPT_DIR/cacti" ]] || die "make completed but ./cacti is not executable"
}

sanitize_run_name() {
  printf '%s' "$1" | sed 's/[^A-Za-z0-9_.-]/_/g'
}

ceil_div() {
  local n="$1"
  local d="$2"
  printf '%d' $(((n + d - 1) / d))
}

csv_escape() {
  local value="${1:-}"
  if [[ "$value" == *','* || "$value" == *'"'* || "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    value="${value//\"/\"\"}"
    printf '"%s"' "$value"
  else
    printf '%s' "$value"
  fi
}

csv_row() {
  local first=1
  local value
  for value in "$@"; do
    if [[ "$first" -eq 0 ]]; then
      printf ','
    fi
    csv_escape "$value"
    first=0
  done
  printf '\n'
}

set_defaults() {
  RUN_NAME="${RUN_NAME:-sram_run}"
  PORT_MODE="${PORT_MODE:-single}"
  WIDTH_BITS="${WIDTH_BITS:-64}"
  DEPTH_WORDS="${DEPTH_WORDS:-1024}"
  TECH_UM="${TECH_UM:-0.028}"
  TEMPERATURE_K="${TEMPERATURE_K:-360}"
  DATA_CELL_TYPE="${DATA_CELL_TYPE:-itrs-hp}"
  DATA_PERIPHERAL_TYPE="${DATA_PERIPHERAL_TYPE:-itrs-hp}"
  FREQUENCY_MHZ="${FREQUENCY_MHZ:-500}"
  READ_ACTIVITY="${READ_ACTIVITY:-1.0}"
  WRITE_ACTIVITY="${WRITE_ACTIVITY:-0.0}"
  UCA_BANK_COUNT="${UCA_BANK_COUNT:-1}"
  WIRE_SIGNALING="${WIRE_SIGNALING:-Global_30}"
  WIRE_INSIDE_MAT="${WIRE_INSIDE_MAT:-semi-global}"
  WIRE_OUTSIDE_MAT="${WIRE_OUTSIDE_MAT:-semi-global}"
  INTERCONNECT_PROJECTION="${INTERCONNECT_PROJECTION:-conservative}"
  PRINT_LEVEL="${PRINT_LEVEL:-DETAILED}"
  FORCE_CACHE_CONFIG="${FORCE_CACHE_CONFIG:-false}"
  NDWL="${NDWL:-1}"
  NDBL="${NDBL:-1}"
  NSPD="${NSPD:-0}"
  NDCM="${NDCM:-1}"
  NDSAM1="${NDSAM1:-0}"
  NDSAM2="${NDSAM2:-0}"
}

require_positive_int() {
  local name="$1"
  local value="$2"
  [[ "$value" =~ ^[0-9]+$ ]] || die "$name must be a positive integer, got '$value'"
  ((value > 0)) || die "$name must be greater than zero"
}

derive_geometry() {
  require_positive_int WIDTH_BITS "$WIDTH_BITS"
  require_positive_int DEPTH_WORDS "$DEPTH_WORDS"

  BLOCK_SIZE_BYTES="$(ceil_div "$WIDTH_BITS" 8)"
  SIZE_BYTES=$((DEPTH_WORDS * BLOCK_SIZE_BYTES))
  PADDED_WIDTH_BITS=$((BLOCK_SIZE_BYTES * 8))
  PADDING_BITS_PER_WORD=$((PADDED_WIDTH_BITS - WIDTH_BITS))
  TOTAL_LOGICAL_BITS=$((DEPTH_WORDS * WIDTH_BITS))
  TOTAL_PADDED_BITS=$((DEPTH_WORDS * PADDED_WIDTH_BITS))
}

derive_ports() {
  case "$PORT_MODE" in
    single)
      RW_PORTS=1
      READ_PORTS=0
      WRITE_PORTS=0
      ;;
    dual)
      RW_PORTS=0
      READ_PORTS=1
      WRITE_PORTS=1
      ;;
    *)
      die "PORT_MODE must be 'single' or 'dual', got '$PORT_MODE'"
      ;;
  esac
}

write_cacti_cfg() {
  local cfg_path="$1"
  cat >"$cfg_path" <<EOF
# Generated by run_sram_analysis.sh for ${RUN_NAME}
# Logical SRAM: ${DEPTH_WORDS} words x ${WIDTH_BITS} bits, ${PORT_MODE} port mode

-size (bytes) ${SIZE_BYTES}
-Array Power Gating - "false"
-WL Power Gating - "false"
-CL Power Gating - "false"
-Bitline floating - "false"
-Interconnect Power Gating - "false"
-Power Gating Performance Loss 0.01

-block size (bytes) ${BLOCK_SIZE_BYTES}
-associativity 1

-read-write port ${RW_PORTS}
-exclusive read port ${READ_PORTS}
-exclusive write port ${WRITE_PORTS}
-single ended read ports 0

-UCA bank count ${UCA_BANK_COUNT}
-technology (u) ${TECH_UM}

-page size (bits) 8192
-burst length 8
-internal prefetch width 8

-Data array cell type - "${DATA_CELL_TYPE}"
-Data array peripheral type - "${DATA_PERIPHERAL_TYPE}"
-Tag array cell type - "${DATA_CELL_TYPE}"
-Tag array peripheral type - "${DATA_PERIPHERAL_TYPE}"

-output/input bus width ${WIDTH_BITS}
-operating temperature (K) ${TEMPERATURE_K}

-cache type "ram"
-tag size (b) "default"
-access mode (normal, sequential, fast) - "normal"

-design objective (weight delay, dynamic power, leakage power, cycle time, area) 0:0:0:0:100
-deviate (delay, dynamic power, leakage power, cycle time, area) 100000:100000:100000:100000:100000

-NUCAdesign objective (weight delay, dynamic power, leakage power, cycle time, area) 0:0:0:0:100
-NUCAdeviate (delay, dynamic power, leakage power, cycle time, area) 100000:100000:100000:100000:100000

-Optimize ED or ED^2 (ED, ED^2, NONE): "NONE"
-Cache model (NUCA, UCA)  - "UCA"
-NUCA bank count 0

-Wire signaling (fullswing, lowswing, default) - "${WIRE_SIGNALING}"
-Wire inside mat - "${WIRE_INSIDE_MAT}"
-Wire outside mat - "${WIRE_OUTSIDE_MAT}"
-Interconnect projection - "${INTERCONNECT_PROJECTION}"

-Core count 8
-Cache level (L2/L3) - "L3"
-Add ECC - "false"

-Print level (DETAILED, CONCISE) - "${PRINT_LEVEL}"
-Print input parameters - "true"
-Force cache config - "${FORCE_CACHE_CONFIG}"
-Ndwl ${NDWL}
-Ndbl ${NDBL}
-Nspd ${NSPD}
-Ndcm ${NDCM}
-Ndsam1 ${NDSAM1}
-Ndsam2 ${NDSAM2}

#### Baseline external IO parameters retained for CACTI cfg compatibility.
-dram_type "DDR3"
-io state "WRITE"
-addr_timing 1.0
-mem_density 4 Gb
-bus_freq 800 MHz
-duty_cycle 1.0
-activity_dq 1.0
-activity_ca 0.5
-num_dq 72
-num_dqs 18
-num_ca 25
-num_clk 2
-num_mem_dq 2
-mem_data_width 8
-rtt_value 10000
-ron_value 34
-tflight_value 0.5
-parallel termination "false"
-package_type "boB"
-num_bobs 1
-capacity 80
-num_channels_per_bob 1
-first metric "Cost"
-second metric "Energy"
-third metric "Bandwidth"
-DIMM model "ALL"
-Low Power Permitted "T"
-load 0.5
-row_buffer_hit_rate 0.5
-rd_2_wr_ratio 0.5
EOF
}

extract_after_label() {
  local label="$1"
  local file="$2"
  awk -v label="$label" '
    index($0, label) {
      value = substr($0, index($0, label) + length(label));
      sub(/^[[:space:]:]*/, "", value);
      print value;
      exit;
    }
  ' "$file"
}

extract_number_after_label() {
  local label="$1"
  local file="$2"
  extract_after_label "$label" "$file" | awk '{ print $1 }'
}

parse_output() {
  local output_path="$1"

  ACCESS_TIME_NS="$(extract_number_after_label 'Access time (ns)' "$output_path")"
  CYCLE_TIME_NS="$(extract_number_after_label 'Cycle time (ns)' "$output_path")"
  DYNAMIC_READ_ENERGY_NJ="$(extract_number_after_label 'Total dynamic read energy per access (nJ)' "$output_path")"
  DYNAMIC_WRITE_ENERGY_NJ="$(extract_number_after_label 'Total dynamic write energy per access (nJ)' "$output_path")"
  LEAKAGE_POWER_MW="$(extract_number_after_label 'Total leakage power of a bank (mW)' "$output_path")"
  GATE_LEAKAGE_POWER_MW="$(extract_number_after_label 'Total gate leakage power of a bank (mW)' "$output_path")"
  DATA_ARRAY_AREA_MM2="$(extract_number_after_label 'Data array: Area (mm2)' "$output_path")"
  BEST_NDWL="$(extract_number_after_label 'Best Ndwl' "$output_path")"
  BEST_NDBL="$(extract_number_after_label 'Best Ndbl' "$output_path")"
  BEST_NSPD="$(extract_number_after_label 'Best Nspd' "$output_path")"
  BEST_NDCM="$(extract_number_after_label 'Best Ndcm' "$output_path")"
  BEST_NDSAM_L1="$(extract_number_after_label 'Best Ndsam L1' "$output_path")"
  BEST_NDSAM_L2="$(extract_number_after_label 'Best Ndsam L2' "$output_path")"

  local dims
  dims="$(extract_after_label 'Cache height x width (mm)' "$output_path")"
  CACHE_HEIGHT_MM="$(printf '%s\n' "$dims" | awk '{ print $1 }')"
  CACHE_WIDTH_MM="$(printf '%s\n' "$dims" | awk '{ print $3 }')"

  if [[ -n "${CACHE_HEIGHT_MM:-}" && -n "${CACHE_WIDTH_MM:-}" ]]; then
    TOTAL_MACRO_AREA_MM2="$(awk -v h="$CACHE_HEIGHT_MM" -v w="$CACHE_WIDTH_MM" 'BEGIN { printf "%.10g", h * w }')"
  else
    TOTAL_MACRO_AREA_MM2=""
  fi

  if [[ -n "${CYCLE_TIME_NS:-}" && "$CYCLE_TIME_NS" != "0" ]]; then
    MAX_FREQUENCY_MHZ="$(awk -v c="$CYCLE_TIME_NS" 'BEGIN { printf "%.10g", 1000 / c }')"
  else
    MAX_FREQUENCY_MHZ=""
  fi

  if [[ -n "${DYNAMIC_READ_ENERGY_NJ:-}" ]]; then
    DYNAMIC_READ_POWER_MW="$(awk -v e="$DYNAMIC_READ_ENERGY_NJ" -v f="$FREQUENCY_MHZ" -v a="$READ_ACTIVITY" 'BEGIN { printf "%.10g", e * f * a }')"
  else
    DYNAMIC_READ_POWER_MW=""
  fi

  if [[ -n "${DYNAMIC_WRITE_ENERGY_NJ:-}" ]]; then
    DYNAMIC_WRITE_POWER_MW="$(awk -v e="$DYNAMIC_WRITE_ENERGY_NJ" -v f="$FREQUENCY_MHZ" -v a="$WRITE_ACTIVITY" 'BEGIN { printf "%.10g", e * f * a }')"
  else
    DYNAMIC_WRITE_POWER_MW=""
  fi

  if [[ -n "${LEAKAGE_POWER_MW:-}" && -n "${GATE_LEAKAGE_POWER_MW:-}" ]]; then
    TOTAL_POWER_MW="$(awk -v l="$LEAKAGE_POWER_MW" -v g="$GATE_LEAKAGE_POWER_MW" -v r="${DYNAMIC_READ_POWER_MW:-0}" -v w="${DYNAMIC_WRITE_POWER_MW:-0}" 'BEGIN { printf "%.10g", l + g + r + w }')"
  elif [[ -n "${LEAKAGE_POWER_MW:-}" ]]; then
    TOTAL_POWER_MW="$(awk -v l="$LEAKAGE_POWER_MW" -v r="${DYNAMIC_READ_POWER_MW:-0}" -v w="${DYNAMIC_WRITE_POWER_MW:-0}" 'BEGIN { printf "%.10g", l + r + w }')"
  else
    TOTAL_POWER_MW=""
  fi
}

write_csv_header() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  csv_row \
    run_name total_macro_area_mm2 total_power_mw status port_mode width_bits depth_words tech_um temperature_k frequency_mhz max_frequency_mhz read_activity write_activity \
    size_bytes block_size_bytes padded_width_bits padding_bits_per_word \
    total_logical_bits total_padded_bits rw_ports read_ports write_ports \
    access_time_ns cycle_time_ns dynamic_read_energy_nj dynamic_write_energy_nj \
    dynamic_read_power_mw dynamic_write_power_mw leakage_power_mw gate_leakage_power_mw data_array_area_mm2 cache_height_mm \
    cache_width_mm best_ndwl best_ndbl best_nspd best_ndcm \
    best_ndsam_l1 best_ndsam_l2 cfg_path output_path >"$path"
}

append_csv_row() {
  local summary_path="$1"
  local status="$2"
  local cfg_path="$3"
  local output_path="$4"

  csv_row \
    "$RUN_NAME" "${TOTAL_MACRO_AREA_MM2:-}" "${TOTAL_POWER_MW:-}" "$status" "$PORT_MODE" "$WIDTH_BITS" "$DEPTH_WORDS" "$TECH_UM" "$TEMPERATURE_K" "$FREQUENCY_MHZ" "${MAX_FREQUENCY_MHZ:-}" "$READ_ACTIVITY" "$WRITE_ACTIVITY" \
    "$SIZE_BYTES" "$BLOCK_SIZE_BYTES" "$PADDED_WIDTH_BITS" "$PADDING_BITS_PER_WORD" \
    "$TOTAL_LOGICAL_BITS" "$TOTAL_PADDED_BITS" "$RW_PORTS" "$READ_PORTS" "$WRITE_PORTS" \
    "${ACCESS_TIME_NS:-}" "${CYCLE_TIME_NS:-}" "${DYNAMIC_READ_ENERGY_NJ:-}" "${DYNAMIC_WRITE_ENERGY_NJ:-}" \
    "${DYNAMIC_READ_POWER_MW:-}" "${DYNAMIC_WRITE_POWER_MW:-}" "${LEAKAGE_POWER_MW:-}" "${GATE_LEAKAGE_POWER_MW:-}" "${DATA_ARRAY_AREA_MM2:-}" "${CACHE_HEIGHT_MM:-}" \
    "${CACHE_WIDTH_MM:-}" "${BEST_NDWL:-}" "${BEST_NDBL:-}" "${BEST_NSPD:-}" "${BEST_NDCM:-}" \
    "${BEST_NDSAM_L1:-}" "${BEST_NDSAM_L2:-}" "$cfg_path" "$output_path" >>"$summary_path"
}

append_batch_total_row() {
  local summary_path="$1"
  local total_area_mm2="$2"
  local total_power_mw="$3"

  csv_row \
    "__TOTAL__" "$total_area_mm2" "$total_power_mw" "summary" "" "" "" "" "" "" "" "" "" \
    "" "" "" "" \
    "" "" "" "" "" \
    "" "" "" "" \
    "" "" "" "" "" "" \
    "" "" "" "" "" \
    "" "" "" "" >>"$summary_path"
}

run_one() {
  local output_root="$1"
  local summary_path="$2"

  set_defaults
  derive_geometry
  derive_ports

  local safe_run_name run_dir cfg_path output_path status
  safe_run_name="$(sanitize_run_name "$RUN_NAME")"
  [[ -n "$safe_run_name" ]] || die "RUN_NAME cannot be empty after sanitization"
  run_dir="$output_root/$safe_run_name"
  cfg_path="$run_dir/generated.cfg"
  output_path="$run_dir/cacti.out"
  mkdir -p "$run_dir"

  write_cacti_cfg "$cfg_path"

  printf 'Running %-24s cfg=%s\n' "$RUN_NAME" "$cfg_path"
  status="ok"
  if ! (cd "$SCRIPT_DIR" && ./cacti -infile "$cfg_path") >"$output_path" 2>&1; then
    status="failed"
  fi

  parse_output "$output_path"
  if [[ "$status" == "ok" && -z "${DYNAMIC_READ_ENERGY_NJ:-}" ]]; then
    status="failed"
  fi

  LAST_RUN_STATUS="$status"
  append_csv_row "$summary_path" "$status" "$cfg_path" "$output_path"
  printf 'Wrote summary row for %s (%s)\n' "$RUN_NAME" "$status"
}

load_single_config() {
  local config_path="$1"
  [[ -f "$config_path" ]] || die "config file not found: $config_path"

  # This intentionally sources trusted local config files for simple KEY=value UX.
  # Do not pass untrusted files.
  # shellcheck disable=SC1090
  source "$config_path"
}

parse_options() {
  while (($#)); do
    case "$1" in
      --out-dir)
        shift
        (($#)) || die "--out-dir requires a value"
        OUT_DIR="$1"
        ;;
      --summary)
        shift
        (($#)) || die "--summary requires a value"
        SUMMARY_PATH="$1"
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
    shift
  done
}

run_single() {
  local config_path="$1"
  shift
  OUT_DIR="$DEFAULT_SINGLE_OUT_DIR"
  SUMMARY_PATH=""
  parse_options "$@"

  load_single_config "$config_path"
  set_defaults

  local safe_run_name output_root summary_path
  safe_run_name="$(sanitize_run_name "$RUN_NAME")"
  output_root="$OUT_DIR"
  summary_path="${SUMMARY_PATH:-$output_root/$safe_run_name/summary.csv}"
  write_csv_header "$summary_path"
  run_one "$output_root" "$summary_path"
  printf 'Summary: %s\n' "$summary_path"
}

reset_run_vars() {
  unset RUN_NAME PORT_MODE WIDTH_BITS DEPTH_WORDS TECH_UM TEMPERATURE_K DATA_CELL_TYPE DATA_PERIPHERAL_TYPE
  unset FREQUENCY_MHZ READ_ACTIVITY WRITE_ACTIVITY
  unset UCA_BANK_COUNT WIRE_SIGNALING WIRE_INSIDE_MAT WIRE_OUTSIDE_MAT INTERCONNECT_PROJECTION PRINT_LEVEL
  unset FORCE_CACHE_CONFIG NDWL NDBL NSPD NDCM NDSAM1 NDSAM2
}

assign_batch_value() {
  local key="$1"
  local value="$2"
  case "$key" in
    run_name) RUN_NAME="$value" ;;
    port_mode) PORT_MODE="$value" ;;
    width_bits) WIDTH_BITS="$value" ;;
    depth_words) DEPTH_WORDS="$value" ;;
    tech_um) TECH_UM="$value" ;;
    temperature_k) TEMPERATURE_K="$value" ;;
    data_cell_type) DATA_CELL_TYPE="$value" ;;
    data_peripheral_type) DATA_PERIPHERAL_TYPE="$value" ;;
    frequency_mhz) FREQUENCY_MHZ="$value" ;;
    read_activity) READ_ACTIVITY="$value" ;;
    write_activity) WRITE_ACTIVITY="$value" ;;
    uca_bank_count) UCA_BANK_COUNT="$value" ;;
    wire_signaling) WIRE_SIGNALING="$value" ;;
    wire_inside_mat) WIRE_INSIDE_MAT="$value" ;;
    wire_outside_mat) WIRE_OUTSIDE_MAT="$value" ;;
    interconnect_projection) INTERCONNECT_PROJECTION="$value" ;;
    print_level) PRINT_LEVEL="$value" ;;
    force_cache_config) FORCE_CACHE_CONFIG="$value" ;;
    ndwl) NDWL="$value" ;;
    ndbl) NDBL="$value" ;;
    nspd) NSPD="$value" ;;
    ndcm) NDCM="$value" ;;
    ndsam1) NDSAM1="$value" ;;
    ndsam2) NDSAM2="$value" ;;
  esac
}

run_batch() {
  local csv_path="$1"
  shift
  [[ -f "$csv_path" ]] || die "batch CSV not found: $csv_path"

  OUT_DIR="$DEFAULT_BATCH_OUT_DIR/$(date +%Y%m%d_%H%M%S)"
  SUMMARY_PATH=""
  parse_options "$@"

  local output_root summary_path header line row_num total_area_mm2 total_power_mw
  output_root="$OUT_DIR"
  summary_path="${SUMMARY_PATH:-$output_root/summary.csv}"
  mkdir -p "$output_root"
  write_csv_header "$summary_path"

  IFS= read -r header <"$csv_path" || die "batch CSV is empty: $csv_path"
  header="${header%$'\r'}"
  IFS=',' read -r -a HEADERS <<<"$header"

  row_num=1
  total_area_mm2="0"
  total_power_mw="0"
  while IFS= read -r line || [[ -n "$line" ]]; do
    row_num=$((row_num + 1))
    line="${line%$'\r'}"
    [[ -z "${line//[[:space:]]/}" ]] && continue
    [[ "${line:0:1}" == "#" ]] && continue

    IFS=',' read -r -a VALUES <<<"$line"
    reset_run_vars
    local i key value
    for i in "${!HEADERS[@]}"; do
      key="$(printf '%s' "${HEADERS[$i]}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/-/_/g' | awk '{ print tolower($0) }')"
      value="${VALUES[$i]:-}"
      value="$(printf '%s' "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
      [[ -z "$value" ]] && continue
      assign_batch_value "$key" "$value"
    done

    [[ -n "${RUN_NAME:-}" ]] || die "row $row_num missing required run_name"
    [[ -n "${PORT_MODE:-}" ]] || die "row $row_num missing required port_mode"
    [[ -n "${WIDTH_BITS:-}" ]] || die "row $row_num missing required width_bits"
    [[ -n "${DEPTH_WORDS:-}" ]] || die "row $row_num missing required depth_words"

    run_one "$output_root" "$summary_path"
    if [[ "${LAST_RUN_STATUS:-}" == "ok" ]]; then
      total_area_mm2="$(awk -v total="$total_area_mm2" -v value="${TOTAL_MACRO_AREA_MM2:-0}" 'BEGIN { printf "%.10g", total + value }')"
      total_power_mw="$(awk -v total="$total_power_mw" -v value="${TOTAL_POWER_MW:-0}" 'BEGIN { printf "%.10g", total + value }')"
    fi
  done < <(sed '1d' "$csv_path")

  append_batch_total_row "$summary_path" "$total_area_mm2" "$total_power_mw"
  printf 'Summary: %s\n' "$summary_path"
}

main() {
  require_tools
  [[ $# -gt 0 ]] || { usage; exit 1; }

  local mode="$1"
  shift
  case "$mode" in
    help|-h|--help)
      usage
      ;;
    single)
      [[ $# -ge 1 ]] || die "single mode requires a config file"
      ensure_cacti_binary
      local config_path="$1"
      shift
      run_single "$config_path" "$@"
      ;;
    batch)
      [[ $# -ge 1 ]] || die "batch mode requires a CSV file"
      ensure_cacti_binary
      local csv_path="$1"
      shift
      run_batch "$csv_path" "$@"
      ;;
    *)
      usage
      die "unknown mode: $mode"
      ;;
  esac
}

main "$@"
